### ISSUE TITLE
Error: Undefined variable: "$spacing-extra-small"

### ISSUE THREAD

**Issue by juicyfish** [tachyons-css/tachyons-sass#10]
Running gulp I am getting:

    Error: Undefined variable: "$spacing-extra-small".
        on line 38 of node_modules/tachyons-sass/scss/_negative-margins.scss
    >> .na1 { margin: -$spacing-extra-small; }

Any ideas?
Thanks

**Comment by talbs** [comment]
@mrmrs, tried to lend a hand with this SCSS error I also encountered with the 4.6 bump. Let me know what you think of the solution/commits and how I can help further.

**Comment by juicyfish** [comment]
Thanks @talbs @mrmrs working fine now.
