### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Kikobeats** [tachyons-css/tachyons-sass#18]
The current `4.7.1` version is not the same than `tachyons@4.7.1`. 

I don't know why, but they don't have available the last changes, such as `.f7` class.

**Comment by pathetix** [comment]
Any updates?
Realized the main tachyons is at v4.7.3 while it is still 4.6.1 for tachyons-sass.

**Comment by antenando** [comment]
Tachyons 4.8.0 is here!

https://github.com/tachyons-css/tachyons/releases/tag/4.8.0

**Comment by pschfr** [comment]
The latest commit (6a95146) shows this was updated to `4.8.0`, but the main `tachyons.sass` file disagrees :unamused:

**Comment by OzzieOrca** [comment]
https://github.com/tachyons-css/tachyons-sass/pull/22

**Comment by johnotander** [comment]
4.8.1 on has been published, thanks all (and @OzzieOrca for the pr)
