### ISSUE TITLE
`.maxs` or `.ma1`?

### ISSUE THREAD

**Issue by roliveira** [tachyons-css/tachyons-sass#2]
I nearly just started using `tachyons` and wanted to try out the sass bit of it. I'm a little lost about the naming convention... For what I could tell you dropped the acronyms for the `v4` in favor of numbers for sizing things, *e.g.* drop `.maxs` in favor of `.ma1`. The commit #1 didn't include that, any plans to update the transpiled sass? 

**great** work btw!

**Comment by johnotander** [comment]
Hey, thanks for opening this issue!

It looks like the transpilation somehow included the old naming scheme for some reason (obviously I didn't review the latest update very closely :blush: ). I'll get digging into this shortly.

**Comment by roliveira** [comment]
Cool! I actually fiddled thought the `Build.js` and couldn't resist to think that this could be automated, say by Travis-CI, and be built whenever you commit something to one of the original tachyons sources.

**Comment by johnotander** [comment]
I like the sound of that : ). Writing the `build.js` was the first step of automation. Now we're at the point where we should automate it running. Would be so rad!

I don't have any experience using Travis CI for automation like that, but would love to hear about how that would work. Have you done this before, or is there a post you could point me to? Also, if you wanted to contribute to implementing this solution, that'd be awesome, too.

**Comment by johnotander** [comment]
Published to npm as `tachyons-sass@4.0.0-beta.20`.
