### ISSUE TITLE
What is the release cycle for this project?

### ISSUE THREAD

**Issue by soypunk** [tachyons-css/tachyons-sass#37]
I was wondering what the release cycle was for this project? I see the main project seems to be officially at v4.11.1 and working on v4.11.2. (Although, I see the docs at https://tachyons.io say v4.10.0) meanwhile the project here seems to be at v4.9.5.

**Comment by orionrush** [comment]
For the current status see: 
https://github.com/tachyons-css/tachyons/issues/645#issuecomment-540896935
