### ISSUE TITLE
How to extend

### ISSUE THREAD

**Issue by niallobrien** [tachyons-css/tachyons-sass#5]
Hi, great project. Just thought it might be a good idea to include a suggestion within the docs on how to extend the Sass version of Tachyons (overriding certain default styles to suit the project at hand). Also, listing all of the variables that can be used within the docs would make it a lot easier for people to get started with regards to extending and customising.

Thanks in advance.

**Comment by ixley** [comment]
I'm curious about this too. Was wondering whether the fact that it's transpiled means it's not a great idea to try and add specific functionality to the Sass repo. For example, it would be awesome to have variables and mixins to make it easier to customize and redefine base values, name codes, etc.

**Comment by gbertb** [comment]
@mrmrs was there a resolution to this? I was wondering about the same issue, too. Please advise. Thanks.
