### ISSUE TITLE
Issue with order of precedence

### ISSUE THREAD

**Issue by aaronrussell** [tachyons-css/tachyons-sass#6]
Using the SASS files in my project, I've noticed an example where the order of precedence is resulting in rules not being applied as expected.

Eg, with the following I'd expect a border-top with 2.5rem thickness...

```html
<div class="bt bw2">Foo bar</div>
```

However, in the generated CSS, the border-width classes appear **before** the border classes, meaning the border-width rules do not override the default 1px border widths.

In contrast the CSS at https://unpkg.com/tachyons@4.5.1/css/tachyons.css shows the border-width classes **after** the border classes, so the width rules successfully override the defaults.

**Comment by johnotander** [comment]
This can now be closed as it is fixed in `4.5.4`, thanks @iansolano!
